apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-node-config
  namespace: default
data:
  README: |
    # GPU Node Configuration Examples
    
    These labels can be applied to Kubernetes nodes to enable specific scheduling behaviors.
    
    ## Cost-Optimized Nodes
    kubectl label nodes <node-name> gpu-orchestrator/cheap-node=true
    
    ## High-Performance Nodes
    kubectl label nodes <node-name> gpu-orchestrator/performance-tier=gpu-a100
    
    ## Example: Label a node for cost optimization
    kubectl label nodes gpu-node-01 gpu-orchestrator/cheap-node=true
---
apiVersion: gpu.warp.dev/v1alpha1
kind: GPUWorkload
metadata:
  name: advanced-example-gpt-finetuning
  namespace: default
spec:
  modelName: gpt-3-finetuning
  gpuCount: 4
  priority: high
  schedulingStrategy: costOptimized
  retryPolicy:
    maxRetries: 5
    backoffSeconds: 30
---
apiVersion: gpu.warp.dev/v1alpha1
kind: GPUWorkload
metadata:
  name: advanced-example-batch-inference
  namespace: default
spec:
  modelName: batch-inference-pipeline
  gpuCount: 2
  priority: normal
  schedulingStrategy: leastLoaded
  retryPolicy:
    maxRetries: 3
    backoffSeconds: 15
---
# Example of monitoring GPU workload scheduling
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: gpu-orchestrator-system
data:
  prometheus-rules.yaml: |
    groups:
    - name: gpu-orchestrator
      interval: 30s
      rules:
      # Alert if GPU workloads are failing to schedule
      - alert: GPUWorkloadSchedulingFailures
        expr: rate(warp_gpuworkload_failed_total[5m]) > 0.1
        for: 5m
        annotations:
          summary: "High GPU workload scheduling failure rate"
          description: "{{ $value | humanizePercentage }} of scheduling attempts are failing"
      
      # Alert if reconciliation is slow
      - alert: SlowGPUWorkloadReconciliation
        expr: histogram_quantile(0.95, warp_gpuworkload_reconcile_duration_seconds) > 5
        for: 5m
        annotations:
          summary: "GPU workload reconciliation is slow"
          description: "95th percentile reconciliation time is {{ $value }}s"
